#!/bin/bash
# Generate a .gitconfig and write it on stdout.


echo -n "Enter name: "
read name
echo -n "Enter email: "
read email

# Generate .gitconfig
OUTFILE="$HOME/.gitconfig"
cat > $OUTFILE <<EOF
[user]
	name = $name
	email = $email
[color]
	ui = true
[alias]
  ci = commit
  st = status
  serve = instaweb -d webrick # requires ruby, leaves server process hanging around
  out = !git fetch && git log FETCH_HEAD..master
  in = !git fetch && git log master..FETCH_HEAD
  glog = !git log --decorate --graph --oneline --all
  ff = !git merge --ff-only
[web]
	browser = google-chrome
[merge]
  tool = kdiff3

EOF
echo "Wrote $OUTFILE"


# Generate .hgrc file
OUTFILE="$HOME/.hgrc"
cat > $OUTFILE <<EOF
[ui]
username = $name <$email>

[extensions]
hgext.extdiff =
hgext.graphlog =
color =
rebase =

[diff]
git = 1

[extdiff]
cmd.cdiff = colordiff
cmd.vdiff = kdiff3

[defaults]
cdiff = -q

EOF
echo "Wrote $OUTFILE"

