#!/bin/bash
set -euo pipefail

main() {
  echo "---"
  echo "NO LONGER INSTALLS DOTFILES, DO IT YOURSELF"
  echo "---"

  # make some dirs my vimrc expects
  mkdir -p "$HOME"/.local/share/vim/{swap,backup,undo}

  echo "Add 'source \"$HOME/dotfiles/home/bashrc_common\"' to your ~/.bashrc"
}

main
