#!/bin/bash

echo -n "Enter name: "
read name
echo -n "Enter email: "
read email

# Generate .gitconfig
OUTFILE="$HOME/.gitconfig"
cat > $OUTFILE <<EOF
[user]
  name = $name
  email = $email
[color]
  ui = true
[alias]
  ci = commit
  st = status
  glog = !git log --decorate --graph --oneline --all
  ff = !git merge --ff-only
[web]
  browser = google-chrome
[merge]
  tool = vimdiff

EOF
echo "Wrote $OUTFILE"


# Generate .hgrc file
OUTFILE="$HOME/.hgrc"
cat > $OUTFILE <<EOF
[ui]
username = $name <$email>

[extensions]
hgext.extdiff =
hgext.graphlog =
color =
rebase =

[diff]
git = 1

[extdiff]
cmd.cdiff = colordiff
cmd.vdiff = kdiff3

[defaults]
cdiff = -q

EOF
echo "Wrote $OUTFILE"

